server:
  port: 9000

spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/backpac-hw"
    username: "jihan"
    password: "jihan"
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        format_sql: true

jwt:
  secretKey: "c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppaGFuLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC10dXRvcmlhbAo="
  tokenPrefix: "Bearer "
  tokenExpirationAfterDays: 1

