server:
  port: 9000

spring:
  datasource:
    driver-class-name: "com.mysql.cj.jdbc.Driver"
    url: "jdbc:mysql://localhost:3306/backpac-hw"
    username: "jihan"
    password: "jihan"
  jpa:
    database: mysql
    hibernate:
#      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_batch_fetch_size: 1000
  sql:
    init:
      mode: always
      data-locations: classpath:/sql/init.sql

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace

jwt:
  secretKey: "c3ByaW5nLWJvb3Qtc2VjdXJpdHktand0LXR1dG9yaWFsLWppaGFuLXNwcmluZy1ib290LXNlY3VyaXR5LWp3dC10dXRvcmlhbAo="
  tokenPrefix: "Bearer "
  tokenExpirationAfterDays: 1

